### ISSUE TITLE
FATAL:  role "root" does not exist

### ISSUE THREAD

**Issue by kawaii** [peter-evans/docker-compose-healthcheck#4]
I notice the following error in my logs appearing every 5 minutes or so:
```
FATAL:  role "root" does not exist
```
Whilst not harmful, and whilst the healthcheck is indeed working as intended (a `docker ps` displays a `(healthy)` status) is there any way to suppress this message? I assume this happens because the official PostgreSQL Docker images do not have a `USER postgres` declaration at the end of their Dockerfiles?

**Comment by peter-evans** [comment]
I'm not aware of this issue so I'll investigate and let you know if I find anything.

**Comment by kawaii** [comment]
Thanks Peter, for reference here is the PostgreSQL snippet from my `docker-compose.yml` file:
```yml
  postgres:
    image: postgres:10.0
    hostname: postgres
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3
    env_file:
      - prosody.env
    volumes:
      - ${PWD}/postgres/data/:/var/lib/postgresql/data/
    restart: always
```
